### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ninehertzandroid** [twilio/twilio-video-app-android#121]
When I passing my token created from my backend in single video call sample is working but when using this sample for multi call unable to login

**Comment by Alton09** [comment]
Hi @ninehertzandroid. Thank you for reaching out. Can you please provide more detail by filling out the [template](https://github.com/twilio/twilio-video-app-android/issues/new?labels=bug&template=bug_report.md) defined in the bug report? This will help us troubleshoot your issue. Thanks!

**Comment by ninehertzandroid** [comment]
Hello @Alton09 

I want to integrate group calling in my app.I have create token from back end but how can i get passcode from this please guide me to use this.

**Comment by Alton09** [comment]
@ninehertzandroid The community build flavor of the video app is intended to be used with the [plugin-rtc](https://github.com/twilio-labs/plugin-rtc) to vend tokens using a passcode. In order to provide your own custom token server, you'll have to do the following:

1. Provide your own `TokenService.kt` implementation, and remove the `AuthServiceRepository.kt`.
1. Remove the passcode UI and add your own auth UI within the `development_activity_login_.xml` layout.
1. Remove the authentication step in the `CommunityAuthenticator`, again you can provide your own implementation here if needed.

Hope that helps!

**Comment by ninehertzandroid** [comment]
@Alton09 Can you send us sample to use group calling?

**Comment by Alton09** [comment]
Hi @ninehertzandroid . Please reach out to [support.twilio.com](https://support.twilio.com/) to get additional help/guidance with this request. Thanks!
