### ISSUE TITLE
Getting black screen for 2 or 3 seconds in primary video view

### ISSUE THREAD

**Issue by braver-tool** [twilio/twilio-video-app-android#184]
##Description

Getting black screen for 2 or 3 seconds in primary video view when rendering remote video track after onVideo TrackSubscribed(screen off/on)

##Steps to Reproduce

1. Connects to the room
2. Remote participant connect to room without videoTrack published
3. Remote participant publish track after some seconds 
4. Manually put screen off using the power button and again on the screen

Twilio SDK version : 6.1.0

Audio Switch : 1.1.0

Testing Device model : Oneplus 7, Motorola g3

Os Version : Android 10, Android 6

Please give any suggestion or source to fix this issue. Thanks in advance...!

**Comment by Alton09** [comment]
Hi @braver-tool . I've tested this scenario on this app and the black preview does not occur. You may want to check out how this app updates the primary view based on changes in the RemoteParticipant VideoTracks. The [RemoteParticipantListener](https://github.com/twilio/twilio-video-app-android/blob/master/app/src/main/java/com/twilio/video/app/sdk/RemoteParticipantListener.kt) contains all of this logic and may be helpful in your scenario. Hope that helps!

**Comment by himanshu-my** [comment]
Hi @Alton09 I am also facing this black screen issue every time when user disable/enable the video track on every device. I have changed the PrimaryParticipantController code like below to achieve my apps functionality. 

` if (identity != "You") {
            val old = primaryItem
            val selectedTrack = screenTrack?.videoTrack ?: videoTrackState?.videoTrack
            val newItem = Item(identity, selectedTrack, muted, mirror)
            // clean old primary video renderings
            old?.let { removeRender(it.videoTrack, primaryView) }

            primaryItem = newItem

            newItem.videoTrack?.let { newVideoTrack ->
                if (newVideoTrack.isEnabled) {
                    newVideoTrack.addSink(primaryView)
                    if (!isFirstFrameAlreadyRendered) {
                        newVideoTrack.addSink {
                            if (!isFirstFrameAlreadyRendered) {
                                isFirstFrameAlreadyRendered = true
                                roomManager.sendRoomEvent(RoomEvent.RemoteParticipantEvent.FirstFrameRendered)
                            }
                        }
                    } else {
                        primaryView.visibility = View.VISIBLE
                    }
                } else {
                    primaryView.visibility = View.GONE
                    roomManager.sendRoomEvent(RoomEvent.RemoteParticipantEvent.RemoteVideoDisabled)
                }
            }
        }`

**Comment by Adilsheikh1** [comment]
@Alton09  Do let us know what further details are required.
This is proving to be a really bad User Experience!

**Comment by Alton09** [comment]
Hi @Adilsheikh1 . The key is to swap out the PrimaryView with a different view that hides the VideoView as quickly as possible in order to avoid seeing a black screen, which is displayed because video is no longer rendered. So after `old?.let { removeRender(it.videoTrack, primaryView) }` then the view needs to be switched right away. This is done in our app with [primaryView.setState(ParticipantView.State.NO_VIDEO)](https://github.com/twilio/twilio-video-app-android/blob/53ecb8f5c412b38fb9bdbe778a120248453decc3/app/src/main/java/com/twilio/video/app/ui/room/PrimaryParticipantController.kt#L49)

**Comment by himanshu-my** [comment]
@Alton09 I have changed the code like below 

```
if (identity != "You") {
            val old = primaryItem
            val selectedTrack = screenTrack?.videoTrack ?: videoTrackState?.videoTrack
            val newItem = Item(identity, selectedTrack, muted, mirror)
            // clean old primary video renderings
            old?.let { removeRender(it.videoTrack, primaryView) }

            primaryItem = newItem

            newItem.videoTrack?.let { newVideoTrack ->
                if (newVideoTrack.isEnabled) {
                    newVideoTrack.addSink(primaryView)
                    if (!isFirstFrameAlreadyRendered) {
                        newVideoTrack.addSink {
                            if (!isFirstFrameAlreadyRendered) {
                                isFirstFrameAlreadyRendered = true
                                roomManager.sendRoomEvent(RoomEvent.RemoteParticipantEvent.FirstFrameRendered)
                            }
                        }
                    } else {
                        //primaryView.visibility = View.VISIBLE
                        roomManager.sendRoomEvent(RoomEvent.RemoteParticipantEvent.RemoteVideoEnabled)
                    }
                } else {
                    primaryView.visibility = View.GONE
                    roomManager.sendRoomEvent(RoomEvent.RemoteParticipantEvent.RemoteVideoDisabled)
                }
            } ?: run {
                primaryView.visibility = View.GONE
                roomManager.sendRoomEvent(RoomEvent.RemoteParticipantEvent.RemoteVideoDisabled)
            }
        }
```

In **run** block I am setting the visibility to gone, but its still working the same way. 

One thing I have observed in twilio-video-app that when user enabling his camera its showing previous state of video to participant for 1-2 secs after that screen is updating with new frames. 

In my case I am seeing black screen instead of old frames.

**Comment by Alton09** [comment]
@himanshu-my Another thing you can try is to set the view state first (i.e. setting visibility) and then calling `old?.let { removeRender(it.videoTrack, primaryView) }` after so that way the renderer is not removed before updating the view. 
> One thing I have observed in twilio-video-app that when user enabling his camera its showing previous state of video to participant for 1-2 secs after that screen is updating with new frames.

I ran a quick manual test with the this app and see the same behavior. I believe this is occurring because we are unpublishing and publishing a new LocalVideoTrack when toggling video (This code can be seen here in the [LocalParticipantManager](https://github.com/twilio/twilio-video-app-android/blob/53ecb8f5c412b38fb9bdbe778a120248453decc3/app/src/main/java/com/twilio/video/app/sdk/LocalParticipantManager.kt#L199)). The ideal thing to do here is to instead enable/disable the LocalVideoTrack as it is a lighter weight operation on the sytem and can possibly clean up this delay of old frames that is seen in the primary video view. I'll look into fixing this in the app in an upcoming sprint.

**Comment by himanshu-my** [comment]
Hi @Alton09 I have resolved the issue when user is enabling the video track by removing the state change callbacks from onVideoTrackEnabled and onVideoTrackDisabled. But when user disables the video track black screen issue is still there. 

To overcome that issue I have applied a hack. I am sending a message from data track to participant for video track disable and in participant side I am removing the video screen immediately, it works fine except in low network cases, because in low network it can take some time to receive the data track message.

**Comment by Alton09** [comment]
Thanks for sharing your workaround @himanshu-my . Sorry you had to go the data track route to get the desired behavior, as this is not what you should have to do to get this working properly. Have you tried running this app on the same devices where you are experiencing this black screen issue and able to reproduce the problem? If so, please do share the device model numbers so I can reproduce it on my end. This issue could also be due to network latency. In the meantime I'll try to run the same test on this app with high network latency to see if I can reproduce the issue.

**Comment by Alton09** [comment]
Yeah just tested with a remote participant device with bad network in another country and am still not seeing the issue within this app.

**Comment by Alton09** [comment]
Closing this one for now due to inactivity.
