### ISSUE TITLE
Handle Orientational Changes for room

### ISSUE THREAD

**Issue by Suyash171** [twilio/twilio-video-app-android#262]
I have used a different layout for the landscape view which needs to restart the activity and recreate things.
In this use case, it recreates everything using localVideoTrack, AudioTrack, Room etc. Is there any solution to handle/ Save instances during orientation, so that their could not be any glitch during recreating it again

**Comment by seancoleman2** [comment]
Hi @Suyash171, can you provide some more information on what you are trying to do and the expected behavior vs. what is happening? Code snippets, errors, a screen recording of what it looks like when you switch to landscape would all be helpful. Would love to help but will need some more info. Thanks!

**Comment by afalls-twilio** [comment]
@seancoleman2 Unfortunately, one can not easily recreate the session when streaming. The recommended solution is to not associate your video code (track creation, connection management, etc) with a fragment and instead either have it associated with the underlying activity or a service.
